### ISSUE TITLE
Switch issue

### ISSUE THREAD

**Issue by fgbustoa** [mshwf/Xamlly#2]
Switch configured as:

OffColor = RED
OnColor = GREEN
OffText = "NO"
OnText = "SI"
IsOn = BOUNDED TO A PERSISTENT bool

1) I set switch to ON: Thumb goes to RIGHT. OK
2) Close page with switch inside
3) Restart page with switch inside
4) I found switch as:
Thumb is on the LEFT, but ... Text = OnText & Color = OnColor

**Comment by mshwf** [comment]
@fgbustoa I don't understand what you mean by "Close page" and "Restart page", I tried `PushAsync` and `PopAsync`, and the control is working normally. It would help identify the issue if you provided a sample project.
Thanks

**Comment by fgbustoa** [comment]
1) When switch IsToggled = FALSE
![NO](https://user-images.githubusercontent.com/55985383/76496680-d48ac880-6439-11ea-876c-e5d5f1e39944.JPG)

2) When switch IsToggled = TRUE
![SI](https://user-images.githubusercontent.com/55985383/76496706-e0768a80-6439-11ea-9d60-9cdc87f6062e.JPG)

3) When i reopen the same page, and button should be Toggled ON
![WRONG](https://user-images.githubusercontent.com/55985383/76496760-fbe19580-6439-11ea-8865-449ed4b1d23d.JPG)

IT'S ONLY A VISUAL ARTIFACT OF THE THUMB: TEXT IS OK, COLOR IS OK, BUT THUMB IS IN WRONG POSITION

BYE

**Comment by mshwf** [comment]
I simply can't reproduce the issue. Can you please attatch a sample project with the issue?

**Comment by fgbustoa** [comment]
I hope this is sufficient for you ....

STYLE

    <ContentPage.Resources>
        <ResourceDictionary>
            <Style TargetType="xamlly:Switch">
                <Setter Property="OnText" Value="SI" />
                <Setter Property="OffText" Value="NO" />
                <Setter Property="OffColor" Value="Red" />
                <Setter Property="OnColor" Value="Green" />
                <Setter Property="CornerRadius" Value="10" />
                <Setter Property="ButtonWidth" Value="40" />
            </Style>
        </ResourceDictionary>
    </ContentPage.Resources>


DEFINITION

                        <xamlly:Switch
                            Grid.Row="0"
                            Grid.Column="1"
                            HorizontalOptions="Start"
                            IsOn="{Binding BarcodeFormatCODE128}"
                            VerticalOptions="Center" />


VIEW MODEL

        public bool BarcodeFormatCODE128
        {
            get { return _BarcodeFormatCODE128; }
            set { SetAndNotify(ref _BarcodeFormatCODE128, value, () => BarcodeFormatCODE128); }
        }

**Comment by mshwf** [comment]
My XAML:
```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:xamlly="clr-namespace:Xamlly.XamllyControls;assembly=Xamlly"
             x:Class="MyXam.ShellPages.Page1">
    <StackLayout HorizontalOptions="Center">
        <Label Text="Welcome to Page1!" VerticalOptions="CenterAndExpand" HorizontalOptions="CenterAndExpand" />
        <xamlly:Switch IsOn="{Binding Agree}"
                       Grid.Row="0" Grid.Column="1" HorizontalOptions="Start" VerticalOptions="Center"/>
        <Button Text="pop" Clicked="Button_Clicked"/>
    </StackLayout>
</ContentPage>
```

App.xaml:

```
<Style TargetType="xamlly:Switch">
    <Setter Property="OnText" Value="SI" />
    <Setter Property="OffText" Value="NO" />
    <Setter Property="OffColor" Value="Red" />
    <Setter Property="OnColor" Value="Green" />
    <Setter Property="CornerRadius" Value="10" />
    <Setter Property="ButtonWidth" Value="40" />
</Style>
```

This is the output:

<img src="https://media.giphy.com/media/gKlPo0wsyNdADm9uKt/giphy.gif"/>

**Comment by fgbustoa** [comment]
i DON'T KNOW WHAT TO SAY ......
THIS IS MY BEHAVIOUR


![MyApp](https://user-images.githubusercontent.com/55985383/76537738-81873480-647e-11ea-9442-86a8eae0908a.gif)

**Comment by mshwf** [comment]
I see other Switches in the page; their "On" direction is on the left rather than right.. Have you customized the control?

**Comment by fgbustoa** [comment]
Absolutely NO

... and yes .... all switches has same problems.

I think that it's not a problem of IPropertyChanges: in that case switch would be RED + "NO" + LEFT THUMB

BYE
.

**Comment by fgbustoa** [comment]
I attach you a DOCX file with sources of the 3 files involved

[Switches.docx](https://github.com/mshwf/Xamlly/files/4329459/Switches.docx)

**Comment by mshwf** [comment]
OK, I created a project with what in the DOCX file, can you please help making it compile and reproduce the issue? there is a missing `PublicModule` member in Impostazioni.xaml.cs file.
The project: https://github.com/mshwf/XamllyIssue02

**Comment by fgbustoa** [comment]
Sorry ...

I included PublicModule.cs in DOCX file. I hope you can compile and test. THANKS FOR YOUR EFFORTS !!!

[Switches.docx](https://github.com/mshwf/Xamlly/files/4331469/Switches.docx)

**Comment by mshwf** [comment]
I need all resources used in Impostazioni.xaml too

**Comment by mshwf** [comment]
I just released a new version fixing this issue, it's a pre-release, so you must check the "Include prerelease" checkbox in VS to see it.

Hope it fixes your issue, and thanks for using Xamlly,
