### ISSUE TITLE
Failed to download the package...

### ISSUE THREAD

**Issue by GaboMendez** [mshwf/Xamlly#5]
Hey !!

I have an issue when i am trying to download the package in my project, i will let you a photo of this problem:

![Untitled](https://user-images.githubusercontent.com/54010882/77580975-44299a80-6eb3-11ea-91d5-ae9aac64cfc2.png)

**Comment by mshwf** [comment]
Seems like you're installing into a portable project not .NET standard. It's recommended that any new project targets .NET standard instead. If it's old project then try to upgrade it.
